# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.4'

volumes:
  chainrefundOrg:
networks:
  cr_network:
     external:
        name: cr_network

services:
  node-app:
    container_name: ttaxrefund.api.blockchain
    image: taxrefund.api.blockchain/nodejs:v1.0.0
    restart: always
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_basic

    working_dir: /usr/src/app
    command: npm start
    volumes:
      - ./:/usr/src/app
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
          condition: on-failure
       placement:
          constraints:
             - node.hostname == ip-172-31-33-161
    ports:
      - published: 3000
        target: 3000
        mode: host
    extra_hosts:
    - "peer0.chainrefundOrg.chainrefund.com:172.31.33.161"
    - "peer0.chainrefundOrg.chainrefund.com:13.231.214.70"
    - "peer0.customsOrg.chainrefund.com:172.31.47.47"
    - "peer0.merchantsOrg.chainrefund.com:172.31.40.38"
    - "peer0.nttOrg.chainrefund.com:172.31.40.83"
    networks:
       cr_network:
          aliases:
             - taxrefund.api.blockchain
